desoto:
  image: christianbladescb/desoto
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  environment:
    - ETCD_HOSTS=http://etcd:4001
    - HOST=172.17.42.1
  links:
    - etcd
etcd: 
  image: quay.io/coreos/etcd
  environment:
    - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:4001
    - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:4001
  ports:
    - "4001:4001"
foo:
  image: alpine:3.2
  ports:
    - "8000:400"
  command: sh -c 'sleep 10000000'